CREATE
readlist_db;

CREATE TABLE BOOK
(
    ID     INTEGER PRIMARY KEY NOT NULL,
    TITLE  VARCHAR(128)        NOT NULL,
    AUTHOR VARCHAR(250)        NOT NULL, `
    GENRE
    `
    VARCHAR
(
    45
) NOT NULL, `MARK`    INTEGER             NOT NULL, `COMMENT` VARCHAR(128)        NOT NULL,
);